[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_KEY}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"
scroll_tesnet = "https://sepolia-rpc.scroll.io/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
